name: goPaint
main: net.arcaniax.gopaint.Main
version: "${version}"
depend: [WorldEdit]
api-version: "1.13"
author: Arcaniax
website: "https://www.spigotmc.org/resources/27717/"

commands:
  gopaint:
    usage: /<command>
    aliases: [ gp ]
    description: GoPaint command

permissions:
  gopaint.world.bypass:
    default: false
  gopaint.plot.bypass:
    default: false
  gopaint.plot.outside:
    default: false
  gopaint.admin:
    default: false
  gopaint.use:
    default: false
