name: Bug report
description: Create a report to help us improve
labels: 'Requires Testing'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for goPaint! Fill out the following form to your best ability to help us fix the problem.
        Only use this if you're absolutely sure that you found a bug and can reproduce it. For anything else, use: [our Discord server](https://discord.com/invite/jpRVrjd).

  - type: dropdown
    attributes:
      label: Server Implementation
      description: Which server Implementation are you using? If your server implementation is not listed, it is not supported. Switch to a supported version first.
      multiple: false
      options:
        - Paper
        - Spigot
        - Tuinity
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Server Version
      description: Which server version version you using? If your server version is not listed, it is not supported. Update to a supported version first.
      multiple: false
      options:
        - '1.20'
        - '1.19.4'
        - '1.19.3'
        - '1.19.2'
        - '1.19.1'
        - '1.19'
        - '1.18.2'
        - '1.18.1'
        - '1.18'
        - '1.17.2'
        - '1.17.1'
        - '1.16.5'
        - '1.15.2'
        - '1.14.4'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce this behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: Error log (if applicable)
      description: If you are reporting a console error, upload any relevant log excerpts to either https://paste.gg/ or https://gist.github.com, save and the paste the link in this box.

  - type: input
    attributes:
      label: Fawe Debugpaste (if applicable)
      description: Run `/fawe debugpaste` in your console or ingame and provide the output link here.

  - type: input
    attributes:
      label: goPaint Version
      description: What version of BetterGoPaint are you running? (`/version BetterGoPaint`)
      placeholder: "For example: BetterGoPaint version 1.0.0-SNAPSHOT+fa92c8abf8a66c08621e66109a64407ec223bdae"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      description: Make sure you have followed each of the steps outlined here.
      options:
        - label: I am using the newest build from https://github.com/TheMeinerLP/BetterGoPaint and the issue still persists.
          required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: You can provide additional context below.
